import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';
import 'package:image_picker/image_picker.dart';
import 'package:percent_indicator/linear_percent_indicator.dart';
import 'package:pie_chart/pie_chart.dart';
import 'package:surveyapp/controller/controller.dart';

import '../model/model.dart';

part 'welcome_view.dart';
part 'admin_add_mandatory.dart';
// part 'admin_add_choicebased.dart';
part 'view_admin_list_category.dart';
part 'view_admin_list_category_add.dart';
part 'view_admin_list_question.dart';
part 'view_admin_list_question_add.dart';
part 'view_home.dart';
part 'view_user_list_question.dart';
part 'view__user_quiz.dart';
part 'view_user_feedback.dart';
part 'view_user_finish_survey.dart';
part 'view_home_admin.dart';
part 'view_admin_mandatory.dart';
//part 'view_admin_choicebased.dart';
part 'view_admin_result_survey.dart';
part 'view_login.dart';
part 'view_register.dart';
part 'view_profile.dart';
part 'view_forget_password.dart';